language: python
python:
  - "3.8"

#
# Install required dependencies
#
install:
  - pip install -r requirements.txt

#
# Run linting and unit tests
#
script:
  - pylint aioweb
  - mypy -p aioweb
  - python -m pytest -v
